//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentAccounting.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breakdown_during_inspection
    {
        public int Id_breaking { get; set; }
        public Nullable<System.DateTime> Date_breaking { get; set; }
        public Nullable<int> Id_inspection { get; set; }
        public Nullable<int> Id_employee { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Technical_inspection Technical_inspection { get; set; }
    }
}
