//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentAccounting.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_failure
    {
        public int Id_equipment_failure { get; set; }
        public string Reason { get; set; }
    }
}
