//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentAccounting.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Technical_inspection = new HashSet<Technical_inspection>();
        }
    
        public int Id_equipment { get; set; }
        public string Name_equipment { get; set; }
        public Nullable<int> Id_type { get; set; }
        public Nullable<int> Id_plot { get; set; }
    
        public virtual Equipment_type Equipment_type { get; set; }
        public virtual Production_plot Production_plot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Technical_inspection> Technical_inspection { get; set; }
    }
}
