//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentAccounting.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сompany
    {
        public int Id_company { get; set; }
        public string Name_company { get; set; }
        public Nullable<int> Id_plot { get; set; }
    
        public virtual Production_plot Production_plot { get; set; }
    }
}
